app = "sale-juntada-api-tomytf13"
primary_region = "gru"
kill_signal = "SIGTERM"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "npx prisma migrate deploy"
  strategy = "rolling"

[env]
  NODE_ENV = "production"
  PORT = "3001"
  ENABLE_SWAGGER = "false"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "20s"
    method = "GET"
    path = "/api/health"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
