ALTER TABLE "Gathering"
ADD COLUMN "dailyStartMinutes" INTEGER NOT NULL DEFAULT 780,
ADD COLUMN "dailyEndMinutes" INTEGER NOT NULL DEFAULT 1440,
ADD COLUMN "slotStepMinutes" INTEGER NOT NULL DEFAULT 480;
